### ISSUE TITLE
AuLink component raises error when used in an ember 3.28 app

### ISSUE THREAD

**Issue by nvdk** [appuniversum/ember-appuniversum#148]
I believe this happens because we always pass `@query` to the LinkTo, even when it's undefined.

There are a couple of solutions we could try:
- wrapping the argument in a getter that returns an empty object when `@query` is falsy
- adding an if statement in the template and not provide the argument to LinkTo if it's not there

I don't know if supplying an empty object is always what we want (might unexpectedly clear queryParams on a route?). So feedback is welcome, the if statement solution seems the safest in any case.

**Comment by Dietr** [comment]
Is this similar to https://github.com/appuniversum/ember-appuniversum/issues/130 ?

**Comment by nvdk** [comment]
yes, looks like it might be a duplicate!

**Comment by Windvis** [comment]
> wrapping the argument in a getter that returns an empty object when `@query` is falsy

I think that might be a good workaround and it would allow us to support v3.27 even if the issue gets fixed in 3.28 :+1:. AFAIK, query params will only reset if you explicitly set them to their default values.

I'm not a fan of the conditional version myself since that would make the implementation very boilerplatey.
