### ISSUE TITLE
AuModal closes unexpectedly

### ISSUE THREAD

**Issue by benjay10** [appuniversum/ember-appuniversum#282]
The AuModal closes unexpectedly in combination with a PowerSelect rendered through wormhole.

Selecting an entry in the PowerSelect by mouse on the AuModal triggers the closing action. We expect selecting not to have any effect on the AuModal state.

**Comment by Windvis** [comment]
This most likely broke due to [this PR](https://github.com/appuniversum/ember-appuniversum/pull/276) (sorry 😅). Before that PR outside clicks didn't close the modal, only backdrop clicks did.

I changed it to close on all outside clicks since I assumed that was exactly the same but I forgot about case where elements can be rendered in a wormhole but still be shown in the modal, which is the case for PowerSelect dropdowns.

To fix this we should return to the previous setup. Outside clicks are allowed, but only backdrop clicks close the modal.
