### ISSUE TITLE
Environment banner

### ISSUE THREAD

**Issue by Dietr** [appuniversum/ember-appuniversum#308]
**Is your feature request related to a problem? Please describe the use case and problem it solves.**
See: https://github.com/lblod/frontend-gelinkt-notuleren-publicatie/pull/57#issuecomment-1212926164

**Describe the solution you'd like**
Move the component to ember appuniversum

**Comment by elpoelma** [comment]
I have created a seperate addon for the environment banner on https://github.com/lblod/ember-environment-banner. We could certainly extract the UI part of it to ember appuniversum.

**Comment by nvdk** [comment]
@Windvis what's your opinion, do we keep it as a separate addon or incorporate it here? I know there was a need for a similar thing on the organization portal, but I don't know how it was solved there.

**Comment by Windvis** [comment]
If it's the intention that most / all Appuniversum applications start displaying the banner then I think it makes sense to move it here, yea. 

I'm a bit hesitant since it uses cli build hooks which aren't supported in v2 addons AFAIK so that would be an extra blocker when we want to make the transition here.

**Comment by Windvis** [comment]
Update: the build hooks of v2 addons are not implemented yet (according to the Discord) so I would refrain from adding it here until that is resolved. Otherwise we're adding extra potential blockers for the v2 conversion of this addon.

What we could do in the meanwhile is adding it as a devDependency and creating a story for it with instructions how to install it and set it up?
