### ISSUE TITLE
Addition of width values for the input component

### ISSUE THREAD

**Issue by brenner-company** [appuniversum/ember-appuniversum#334]
Within Kaleidos we have the possibility to define a few width values (`small`, `medium`, `large`, etc.) in addition to `block` for our own input component. For example: we use this in case we need to display an input for a prefix with only 5 digits/letters.

Is this something that could also be added to the `AuInput` component (like `<AuInput @size="small">`) or is it advisable to wrap the input inside an element with a helper class?

**Comment by Windvis** [comment]
It feels a bit strange since the actual values depend on the project I guess? I assume that means we would have to expose some sass / css variables as "public" api?

**Comment by brenner-company** [comment]
> It feels a bit strange since the actual values depend on the project I guess? I assume that means we would have to expose some sass / css variables as "public" api?

That is correct 👍 But if you think this will add extra unnecessary complexity, feel free to say so.

**Comment by Windvis** [comment]
Personally I see little benefit of `<AuInput @width="small" />` over:
- custom css classes for one-off edge cases
- custom size css utils that fit the project
- custom components for more common use-cases

Even if this feature was added I still would prefer using a wrapper instead of having to type the width argument each time. Usually the component then has a more descriptive name so the template is more readable.

But this is all subjective of course, others might think otherwise 😄.

**Comment by Dietr** [comment]
You could use the max-width utility classes together with the `@width="block"` setting.

**Comment by brenner-company** [comment]
@Windvis I'm cool with that 👍 I think we overcomplicate some components in Kaleidos that way. Always good to hear another point of view.

@Dietr I think I'll adopt your solution, thanks!
