### ISSUE TITLE
Update to v2 lockfiles or document need for old npm

### ISSUE THREAD

**Issue by abeforgit** [appuniversum/ember-appuniversum#342]
Bit unclear for contributors what the policy is on what node/npm version to use.

I'd recommend moving to the latest lts, we've been using it all across GN and haven't really hit anything weird.
The biggest change is the way peerdeps are handled but this project doesn't define any so I don't think it will make too many waves.

**Comment by Windvis** [comment]
This addon still officially supports npm 12 (and that's also used in CI) so that's what I would use locally. In practice I think node 14 is used since that's what's defined in the .nvmrc file.

We're pretty close to v2 which drops node 12. We could also drop node 14 while we're at it and switch to node 18 + npm 8+.

Maybe it would be better to simply drop the node requirement from the readme since I'm not sure why it even matters for client side only addons. (The current setup simply follows the Ember blueprint.)

**Comment by Windvis** [comment]
It seems I documented it in [this commit](https://github.com/appuniversum/ember-appuniversum/commit/8a81fd1dff48a7bd15f69e0885cf46a4e1c7ba8d) but forgot to close the issue.
