### ISSUE TITLE
AuAlert icon alignment for "small" size seems wrong

### ISSUE THREAD

**Issue by abeforgit** [appuniversum/ember-appuniversum#388]
**Describe the bug**
When you use an AuAlert with a "small" size, with both a title and block-content, the icon aligns to the title and not in the middle.
To me this seems wrong but if this is intentional feel free to close the ticket.

**Screenshots**

![image](https://user-images.githubusercontent.com/16419862/225000370-8f76fab3-3bd3-4506-9ed0-d1bb495cdead.png)

**Comment by abeforgit** [comment]
for reference, the large (default) size looks like this, aka center-aligned:
![image](https://user-images.githubusercontent.com/16419862/225001064-59de9451-35f7-4bf3-8f90-b0b64b3f0694.png)

**Comment by Windvis** [comment]
I think the circle is aligned to the top in both cases, but it's more obvious for the small version. When the content grows in height the large circle still stays in the same place (as can be seen in the [Storybook example](https://appuniversum.github.io/ember-appuniversum/?path=/story/components-notifications-aualert--component) if you resize the screen)

I assume it was intentional, but maybe we could add an `@align` argument or something to make it configurable?

**Comment by abeforgit** [comment]
Ah yes I see. It somehow feels less jarring with the large version
